import Duper.Tactic
import Duper.TPTP
import Duper.Util.InspectCoreM
import Lean

open Lean

def codegen : CoreM Unit := do
  let mut file := #[]
  file := file.push "import Lean"
  file := file.push "import Duper.Tactic"
  file := file.push "import Duper.TPTP"
  file := file.push "open Lean"
  file := file.push "-- Desperate time, desperate measures"
  file := file.push "-- This file is generated by RestoreCoreMCodeGen.lean"
  file := file.push ""
  file := file.push "-- Names being added:"
  let names ← Duper.inspectCoreM "Duper"
  for name in names do
    file := file.push ("  -- " ++ name.toString)
  file := file.push (← Duper.addNamesToCoreM "restoreCoreM" names)
  IO.FS.writeFile "RestoreCoreM.lean" (String.intercalate "\n" file.toList)

#eval codegen